# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b9818f0129766c4c11b5ef0cfec6b3ec125a46c38814a24a6a013e1ded199542c6c2b53afe1594a3fa1814122dc594c09338c5983f52299f88f75f91c9b75a
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

test:
  secret_key_base: bc04a989a3a389b29e0de9380dd813a2f64484894fd80f4069d0ecfb9b30b43c0f8ac1dcc52b155fe65f4c1d9f8b1903a2652629071ee04f28d6a868cbb33920
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  auth0_domain: <%= ENV["AUTH0_DOMAIN"] %>
  auth0_api_audience: <%= ENV["AUTH0_API_AUDIENCE"] %>
